### ISSUE TITLE
Segmentation fault while indexing

### ISSUE THREAD

**Issue by ghost** [chhylp123/BitMapperBS#17]
Hello, 
I am really eager to test your software but I got an error at the very first step (see below).
I have ubuntu 18.04 and I just downloaded BitMapper 1.0.2.3
Any ideas what could be wrong?
Thanks,
Sol

$ ./bitmapperBS --index /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.Ens.all.fa
fileName[0]: /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.Ens.all.fa
fileName[1]: /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.Ens.all.fa.index
Generating Index from /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.Ens.all.fa
>
Chrome Name =1 ********
>
Chrome Name =10 ********
>
Chrome Name =11 ********
>
Chrome Name =12 ********
>
Chrome Name =13 ********
>
Chrome Name =14 ********
>
Chrome Name =15 ********
>
Chrome Name =16 ********
>
Chrome Name =17 ********
>
Chrome Name =18 ********
>
Chrome Name =19 ********
>
Chrome Name =2 ********
>
Chrome Name =20 ********
>
Chrome Name =21 ********
>
Chrome Name =22 ********
>
Chrome Name =3 ********
>
Chrome Name =4 ********
>
Chrome Name =5 ********
>
Chrome Name =6 ********
>
Chrome Name =7 ********
>
Chrome Name =8 ********
>
Chrome Name =9 ********
>
Chrome Name =MT ********
>
Chrome Name =X ********
>
Chrome Name =Y ********
Chrome Name =1 ********
Chrome length =248956422 ********
Chrome Name =10 ********
Chrome length =133797422 ********
Chrome Name =11 ********
Chrome length =135086622 ********
Chrome Name =12 ********
Chrome length =133275309 ********
Chrome Name =13 ********
Chrome length =114364328 ********
Chrome Name =14 ********
Chrome length =107043718 ********
Chrome Name =15 ********
Chrome length =101991189 ********
Chrome Name =16 ********
Chrome length =90338345 ********
Chrome Name =17 ********
Chrome length =83257441 ********
Chrome Name =18 ********
Chrome length =80373285 ********
Chrome Name =19 ********
Chrome length =58617616 ********
Chrome Name =2 ********
Chrome length =242193529 ********
Chrome Name =20 ********
Chrome length =64444167 ********
Chrome Name =21 ********
Chrome length =46709983 ********
Chrome Name =22 ********
Chrome length =50818468 ********
Chrome Name =3 ********
Chrome length =198295559 ********
Chrome Name =4 ********
Chrome length =190214555 ********
Chrome Name =5 ********
Chrome length =181538259 ********
Chrome Name =6 ********
Chrome length =170805979 ********
Chrome Name =7 ********
Chrome length =159345973 ********
Chrome Name =8 ********
Chrome length =145138636 ********
Chrome Name =9 ********
Chrome length =138394717 ********
Chrome Name =MT ********
Chrome length =16569 ********
Chrome Name =X ********
Chrome length =156040895 ********
Chrome Name =Y ********
Chrome length =57227415 ********
The length of Genome is 3088286401:
Segmentation fault (core dumped)

**Comment by chhylp123** [comment]
Hi,

Have you ever tried the version in conda? It is also BitMapper 1.0.2.3.

**Comment by ghost** [comment]
Hi chhylp123, 

Thank you for your advise. I tried now with the bioconda installation and it gave the same error, just that it took one hour to give the "Segmentation fault" error while with the source version the message came right after. What else can I try?

Thanks,
Sol

**Comment by chhylp123** [comment]
> Hi chhylp123,
> 
> Thank you for your advise. I tried now with the bioconda installation and it gave the same error, just that it took one hour to give the "Segmentation fault" error while with the source version the message came right after. What else can I try?
> 
> Thanks,
> Sol

Sorry for late reply. Could provide the link to your reference genome, and the command lines you have used? I would like to have a look why we have this bug. Thanks a lot.

**Comment by ghost** [comment]
Hi chhylp123, 

It is the human genome: **Homo_sapiens** from here: 
 ftp://ftp.ensembl.org/pub/release-91/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

The command liine and first lines of output:
```
$ /usr/bin/miniconda3/bin/bitmapperBS --index /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
fileName[0]: /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
fileName[1]: /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.index
Generating Index from /mnt/data/Genomes/hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa
>
Chrome Name =1 ********
>
[ ....... ]
Chrome Name =KI270394.1 ********
Chrome length =970 ********
The length of Genome is 3099750718:
Segmentation fault (core dumped)
```


Thanks,
Sol

**Comment by ghost** [comment]
Hi chhylp123, 

I changed some naming of fasta entries and it seems to have worked but I still have a segmentation fault at the end of the output, can I use this index or is there still a problem?

```
Read files are in compressed FASTQ format...
Open /mnt/data/Genomes/hg38_gemBS/Homo_sapiens.GRCh38.dna.primary_assembly_spikein.fa.index sucessfully!
Start load hash table!
refGenLength = 0
Open /mnt/data/Genomes/hg38_gemBS/Homo_sapiens.GRCh38.dna.primary_assembly_spikein.fa.index.bs.pac sucessfully!
shapline=0
BWT has been loaded!
hash table has been loaded!
SA_length=0
sparse_suffix_array_length=0
SA_flag_iterater=0
high_occ_table_length=0
Start alignment in default fast mode.
Welcome to BitMapperBS!
Segmentation fault (core dumped)
```

**Comment by xuefei6600** [comment]
I ran into the same problem (1.0.2.3), which seemed to run if I soft-linked psascan to the reference genome directory. Otherwise the index will fail and prompt 
```
...
Chrome length =58617616 ********
Chrome Name =20 ********
Chrome length =64444167 ********
Chrome Name =21 ********
Chrome length =46709983 ********
Chrome Name =22 ********
Chrome length =50818468 ********
Chrome Name =X ********
Chrome length =156040895 ********
Chrome Name =Y ********
Chrome length =57227415 ********
Chrome Name =MT ********
Chrome length =16569 ********
The length of Genome is 3088286401:
Open human_B38.fa.index.bs sucessfully!
rm: cannot remove ‘tmp_ref.tmp.sa5’: No such file or directory
the binary of psascan does not exist...
sh: psascan: command not found
/opt/gridengine/default/spool/tjcompute038/job_scripts/1526176: line 3: 419228 Segmentation fault      (core dumped) /path/miniconda3/envs/wgbs/bin/bitmapperBS --index human_B38.fa
```

**Comment by Myskiper** [comment]
> Hi chhylp123,
> I meet the same problem(1.0.2.3). 
> I changed reference genome,some thing like ">HLA-A*01:01:01:01 HLA0001 3503bp" to ">HLA0001 3503bp". then the error occurred.Any solutions?
> Thanks,

**Comment by chhylp123** [comment]
Can you find a binary named 'psascan' at the working directory? Or can you give me a small example with changed name?

**Comment by Myskiper** [comment]
sorry, I re-index the genome, and get error message
"
rm: 无法删除"tmp_ref.tmp.sa5": 没有那个文件或目录
the binary of psascan does not exist...
"
but the task didn't interupt and log end with this
 "
Computation finished. Summary:
  elapsed time: 3444.66s (0.5613s/MiB)
  speed: 1.78MiB/s
text_length =6434693834, file_length=6434693834
text_length = file_length...sucess...
bwt_length=201084183,occ_byte_length=50271047, bwt_length+occ_byte_length=251355230
write SA_length=2139726539, shapline=3009633547
SA_flag has been built
sparse_suffix_array_length=804336730
SA_flag_iterater=125677616
Sucess!
command_string: rm Homo_sapiens_assembly38.fasta.index.bs

DONE in 11070.08s!
text_length=6434693834
SA has been generated!
Occ and BWT have been built!
Occ has been writed!
BWT has been writed!
cc&sharp_line has been writed!
hash table has been writed!
"
so maybe the problem is the "error message".

**Comment by chhylp123** [comment]
The log information said: "the binary of psascan does not exist...". It should be a psascan file at the working folder. May I ask how did you install bitmapperbs? Thanks a lot.

**Comment by Myskiper** [comment]
i install psascan and bitmapperBS in same dir,but my workdir is't this. So i export install_dir
use command as:


export PATH=/install_dir:$PATH
install_dir/bitmapperBS --index Homo_sapiens_assembly38.fasta



and get log error:
...
The length of Genome is 3217346917:
Open Homo_sapiens_assembly38.fasta.index.bs sucessfully! 
rm: 无法删除"tmp_ref.tmp.sa5": 没有那个文件或目录
the binary of psascan does not exist...

...
Computation finished. Summary:
&nbsp; elapsed time: 3444.66s (0.5613s/MiB)
&nbsp; speed: 1.78MiB/s
text_length =6434693834, file_length=6434693834
text_length = file_length...sucess...
bwt_length=201084183,occ_byte_length=50271047, bwt_length+occ_byte_length=251355230
write SA_length=2139726539, shapline=3009633547
SA_flag has been built
sparse_suffix_array_length=804336730
SA_flag_iterater=125677616
Sucess!
command_string: rm Homo_sapiens_assembly38.fasta.index.bs
DONE in 11070.08s!
text_length=6434693834
SA has been generated!
Occ and BWT have been built!
Occ has been writed!
BWT has been writed!
cc&amp;sharp_line has been writed!
hash table has been writed!

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chhylp123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 上午8:06
收件人:&nbsp;"chhylp123/BitMapperBS"<BitMapperBS@noreply.github.com&gt;;
抄送:&nbsp;"吴美珍"<875362384@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chhylp123/BitMapperBS] Segmentation fault while indexing (#17)





 
The log information said: "the binary of psascan does not exist...". It should be a psascan file at the working folder. May I ask how did you install bitmapperbs? Thanks a lot.

**Comment by chhylp123** [comment]
Bitmapperbs requires pascan when building index. So you need to make pascan available for bitmapperbs. Can you give a soft link to pascan at the working folder of bitmapperbs, or set the environment variable for pascan?

**Comment by biubiu-1** [comment]
I run into a similar problem with bitmapperBS(v1.0.2.3) installed by conda. I checked that psascan was installed properly by conda, but there was still an error: 'the binary of psascan does not exist'. After adding a soft link of psascan to my work directory, it turned to be 'the binary of psascan exists.'. However the program still failed with 'core dump'.

**Comment by chhylp123** [comment]
I‘m so sorry for the delay. I will fix this problem this week..’

**Comment by dpryan79** [comment]
Does psascan need to be in the working directory, in the same directory that BitMapperBS is in, or just somewhere in your PATH? I have a colleague who also just ran into this issue and for him it worked to recompile psascan rather than to use the (working) version from conda, which suggests that there's just a simple implementation issue causing this series of segfaults for people.

**Comment by dpryan79** [comment]
Ah, I see, either in the working directory or somewhere in your $PATH should work:

https://github.com/chhylp123/BitMapperBS/blob/d0fb1ea7b7ecc92b8182068b2f096c33d20c7d68/bwt.cpp#L1031-L1042

You might change `psascan not found` to `psascan not found in your working directory, assuming it's in your $PATH` in the code.

**Comment by chhylp123** [comment]
Thanks for pointing this issue. I'm rewriting the index part to avoid psascan and hope to release it soon.

**Comment by dpryan79** [comment]
@chhylp123 Thanks. For whatever it's worth the issue seems to be that the file given to psascan is binary rather than text, causing it to segfault.

**Comment by chhylp123** [comment]
@dpryan79 Just curious have you really seen any example that the input file of psascan is binary? I'm rewriting the index part in BWA-like way so psascan will be totally avoided.  I'm pretty busy last year and just have time to fix the problems / do code cleaning of BitMapperBS recently.  Thanks a lot for your great help!

**Comment by dpryan79** [comment]
@chhylp123 No, I've never used psascan directly before, I was just modifying the bitmapperBS code to debug the cause of the segfault my colleage was running into and noticed that the file it's receiving is a binary representation of a text file.
